theme: jekyll-theme-minimal
title : Repositorio
author : Andrés González Santa Cruz,
email : gonzalez.santacruz.andres@gmail.com
encoding: utf-8
language: es
description: |
  Tesis
navbar:
  right:
    - text: "Home"
      href: index.html
    - text: "About"
      href: about.html