app <- ShinyDriver$new("../../")
app$snapshotInit("mytest")

app$setInputs(a = "asdasd")
app$setInputs(b = -1)
app$setInputs(b = -2)
app$setInputs(b = -5)
app$setInputs(b = -6)
app$setInputs(b = -5)
app$setInputs(b = -4)
app$setInputs(b = -3)
app$setInputs(b = -2)
app$setInputs(b = -1)
app$setInputs(b = 0)
app$setInputs(b = 1)
app$setInputs(c = "asdasd")
app$setInputs(`next-1` = "click")
app$setInputs(e = "Paquetes, funciones,etc.")
app$setInputs(d = "asdads")
app$setInputs(f = "Una distribución simétrica")
app$setInputs(g = "Estos componentes también se llaman 'capas'")
app$setInputs(h = "Verdadero")
app$setInputs(i = "Verdadero")
app$setInputs(submit = "click")
app$snapshot()
